server:
  port: 9092

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sales?useSSL=false
    username: root
    password: password
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
logging:
  level:
    com.nana: DEBUG
    org.springframework.security: DEBUG
        
